### ISSUE TITLE
v2来的，希望作者提供一个docker镜像，本地部署太麻烦了。 Please provide docker image for LafTools,  it's not convenient to build LafTools from repo.

### ISSUE THREAD

**Issue by gclm** [work7z/LafTools#27]

**Comment by work7z** [comment]
感谢同学反馈！

LafTools会提供docker版本的，目前在线版部署就是docker镜像实现。

但由于版本还没发布正式版本，等2.0.0正式发布之后，docker镜像和桌面端也会一并发布，敬请期待哈

Thanks, we will be working on it and release its first docker image asap.

**Comment by a18ccms** [comment]
感觉这个工具超酷！支持！

**Comment by work7z** [comment]
@a18ccms 感谢同学支持 :P

**Comment by work7z** [comment]
![image](https://github.com/work7z/LafTools/assets/60811462/9952a765-c32b-44d4-b013-f143e13a0a3c)


很高兴告诉这个消息，现在docker版本今已正式发布，可按照仓库的方式进行docker容器的配置，并且后续任何更新都可以实时推送更新
